test:
	go test -v ./...

build: test
	go build -o ./bin ./cmd/...

run:
	go run cmd/classroom/main.go

pre-build: test
	GOOS=linux GOARCH=amd64 go build -o ./bin/linux/ ./cmd/...
	GOOS=windows GOARCH=amd64 go build -o ./bin/windows/ ./cmd/...
	GOOS=darwin GOARCH=amd64 go build -o ./bin/darwin/ ./cmd/...
	